// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHGBwyj4mlM3lp6B5nGV3bDHVkv7fsOLU',
    appId: '1:158509263976:web:774952a85fb9a8b3379fdd',
    messagingSenderId: '158509263976',
    projectId: 'herbalance-ai-f0ab2',
    authDomain: 'herbalance-ai-f0ab2.firebaseapp.com',
    storageBucket: 'herbalance-ai-f0ab2.firebasestorage.app',
    measurementId: 'G-DYYGYQMTHH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZhPzZngA6ffMXMN-j94TcD74vgVpSyD8',
    appId: '1:158509263976:android:1726ff356709b76a379fdd',
    messagingSenderId: '158509263976',
    projectId: 'herbalance-ai-f0ab2',
    storageBucket: 'herbalance-ai-f0ab2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjpiVywuAnpGroNJCm5lZ1aVwV7GODaTQ',
    appId: '1:158509263976:ios:51a1e4476f090875379fdd',
    messagingSenderId: '158509263976',
    projectId: 'herbalance-ai-f0ab2',
    storageBucket: 'herbalance-ai-f0ab2.firebasestorage.app',
    iosBundleId: 'com.example.herbalanceNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjpiVywuAnpGroNJCm5lZ1aVwV7GODaTQ',
    appId: '1:158509263976:ios:51a1e4476f090875379fdd',
    messagingSenderId: '158509263976',
    projectId: 'herbalance-ai-f0ab2',
    storageBucket: 'herbalance-ai-f0ab2.firebasestorage.app',
    iosBundleId: 'com.example.herbalanceNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHGBwyj4mlM3lp6B5nGV3bDHVkv7fsOLU',
    appId: '1:158509263976:web:ddecd759fa220443379fdd',
    messagingSenderId: '158509263976',
    projectId: 'herbalance-ai-f0ab2',
    authDomain: 'herbalance-ai-f0ab2.firebaseapp.com',
    storageBucket: 'herbalance-ai-f0ab2.firebasestorage.app',
    measurementId: 'G-VKZ9EHMJ63',
  );
}
